# Labels for PRs based on changed files

frontend:
  - changed-files:
      - any-glob-to-any-file:
          - "src/app/**/*"
          - "src/components/**/*"
          - "public/**/*"

backend:
  - changed-files:
      - any-glob-to-any-file:
          - "src/api/**/*"
          - "src/lib/**/*"
          - "src/server/**/*"

prisma:
  - changed-files:
      - any-glob-to-any-file:
          - "prisma/**/*"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "*.md"
          - "swagger.yaml"

config:
  - changed-files:
      - any-glob-to-any-file:
          - "*.json"
          - "*.config.*"
          - ".gitignore"
          - ".github/**/*"
