use soroban_sdk::contracttype;

/// Per-user savings account state with strict principal / yield separation.
///
/// The `principal` field records the user's raw USDC deposits — their baseline
/// liquidity in the savings module. The `yield_shares` field tracks the user's
/// proportionate entitlement to yield generated by external DeFi protocols
/// (AMM / Blend). Keeping these two quantities completely isolated prevents
/// accounting errors that could arise if savings funds were co-mingled with
/// other contract state (e.g. time-locked gift escrows).
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct UserSavings {
    /// Total amount of raw USDC deposited by the user — their baseline
    /// liquidity. Only grows via deposits; never decreased by yield
    /// withdrawals.
    pub principal: i128,
    /// Accounting integer tracking the user's proportionate entitlement
    /// to the yield generated by external DeFi protocols (AMM / Blend).
    /// Increases when yield is accrued; decreases when yield is withdrawn.
    pub yield_shares: i128,
}
